/**
 * Phase 9 — Invoice Rejection & Reversal
 * 25 tests: rejection effects, reversal of financial operations
 */
import { test, expect } from '../fixtures/auth.fixture';

test.describe('P9-IRR: Invoice Rejection & Reversal', () => {
    test('P9-IRR1: Admin can approve invoice', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR2: Admin can reject invoice', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR3: Accountant can approve invoice', async ({ accountantPage }) => { await accountantPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await accountantPage.waitForLoadState('networkidle').catch(() => { }); await accountantPage.waitForTimeout(2000); const b = await accountantPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR4: Accountant can reject invoice', async ({ accountantPage }) => { await accountantPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await accountantPage.waitForLoadState('networkidle').catch(() => { }); await accountantPage.waitForTimeout(2000); const b = await accountantPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR5: GM cannot approve invoice', async ({ gmPage }) => { await gmPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await gmPage.waitForLoadState('networkidle').catch(() => { }); await gmPage.waitForTimeout(2000); const b = await gmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR6: Employee cannot approve own invoice', async ({ pePage }) => { await pePage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR7: Rejection returns CUSTODY amount', async ({ adminPage }) => { await adminPage.goto('/projects', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR8: Rejection deletes PERSONAL debt', async ({ adminPage }) => { await adminPage.goto('/debts', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR9: Rejection returns COMPANY_DIRECT wallet', async ({ adminPage }) => { await adminPage.goto('/wallet', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IRR10: Rejection notification sent to creator', async ({ adminPage }) => { await adminPage.goto('/notifications', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR11: Rejected invoice status badge', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR12: Approved invoice status badge', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR13: Pending invoice status badge', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR14: Approved→Pending transition allowed', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR15: Rejected→Pending transition allowed', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR16: Approval notification sent', async ({ adminPage }) => { await adminPage.goto('/notifications', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR17: Approval records approvedBy', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR18: Approval records approvedAt', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR19: Rejection records rejectedBy', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR20: Invoice detail shows approval history', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const l = adminPage.locator('a[href*="/invoices/"]').first(); if (await l.count() > 0) { await l.click(); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); } const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR21: SPLIT rejection returns both', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR22: Double approval prevented', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR23: Double rejection prevented', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR24: Invoice count in project detail', async ({ adminPage }) => { await adminPage.goto('/projects', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const l = adminPage.locator('a[href*="/projects/"]').first(); if (await l.count() > 0) { await l.click(); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); } const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IRR25: Invoice total in reports', async ({ adminPage }) => { await adminPage.goto('/reports', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
});
