/**
 * Phase 9 — Invoice Company Direct
 * 20 tests: COMPANY_DIRECT payment, wallet deduction, category requirement
 */
import { test, expect } from '../fixtures/auth.fixture';

test.describe('P9-ICD: Invoice Company Direct', () => {
    test('P9-ICD1: COMPANY_DIRECT option for admin', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD2: COMPANY_DIRECT option for accountant', async ({ accountantPage }) => { await accountantPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await accountantPage.waitForLoadState('networkidle').catch(() => { }); await accountantPage.waitForTimeout(2000); const b = await accountantPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD3: COMPANY_DIRECT hidden for employee', async ({ pePage }) => { await pePage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD4: Company expense requires category', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD5: Category dropdown shows COMPANY scope', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD6: Company invoice wallet deduction link', async ({ adminPage }) => { await adminPage.goto('/wallet', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD7: Company invoice in company tab', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD8: Company invoice detail shows badge', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const l = adminPage.locator('a[href*="/invoices/"]').first(); if (await l.count() > 0) { await l.click(); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); } const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD9: Company invoice project optional', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD10: Company invoice approval by admin/accountant', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD11: Company invoice rejection returns wallet', async ({ adminPage }) => { await adminPage.goto('/wallet', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD12: Company invoice reports section', async ({ adminPage }) => { await adminPage.goto('/reports', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD13: Company invoice in dashboard stats', async ({ adminPage }) => { await adminPage.goto('/', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-ICD14: Company invoice no custody deduction', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD15: Company invoice no debt creation', async ({ adminPage }) => { await adminPage.goto('/debts', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD16: GM sees company invoices', async ({ gmPage }) => { await gmPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await gmPage.waitForLoadState('networkidle').catch(() => { }); await gmPage.waitForTimeout(2000); const b = await gmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD17: GM cannot approve company invoices', async ({ gmPage }) => { await gmPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await gmPage.waitForLoadState('networkidle').catch(() => { }); await gmPage.waitForTimeout(2000); const b = await gmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD18: Outsider cannot see company invoices', async ({ outsiderPage }) => { await outsiderPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await outsiderPage.waitForLoadState('networkidle').catch(() => { }); await outsiderPage.waitForTimeout(2000); const b = await outsiderPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(20); });
    test('P9-ICD19: Invoice voucher for company direct', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-ICD20: Company invoice search works', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
});
