/**
 * Phase 9 — Invoice Items Validation + Voucher PDF + Manager Implicit + Edge Amounts
 * 55 tests combined
 */
import { test, expect } from '../fixtures/auth.fixture';

test.describe('P9-IIV: Invoice Items Validation', () => {
    test('P9-IIV1: Add item button visible', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV2: Remove item button', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV3: Item description field', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV4: Item quantity field', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV5: Item price field', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV6: Item total auto-calculated', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV7: Grand total = sum of items', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV8: No items uses manual amount', async ({ pePage }) => { await pePage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IIV9: Items visible in detail page', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const l = adminPage.locator('a[href*="/invoices/"]').first(); if (await l.count() > 0) { await l.click(); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); } const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IIV10: Items in PDF voucher', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IIV11: Quantity 0 rejected', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV12: Price 0 rejected', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV13: Up to 20 items allowed', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV14: Description required for items', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IIV15: Items toggle optional', async ({ pePage }) => { await pePage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
});

test.describe('P9-IVP: Invoice Voucher PDF', () => {
    test('P9-IVP1: Voucher accessible from detail', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP2: Voucher shows reference', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP3: Voucher shows amount', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP4: Voucher shows project', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP5: Voucher shows creator', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP6: Voucher print button', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP7: Voucher A4 layout', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP8: Voucher shows items table', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP9: Voucher shows date', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IVP10: Voucher shows payment source', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
});

test.describe('P9-IMI: Invoice Manager Implicit', () => {
    test('P9-IMI1: Manager can create invoice as PM', async ({ pmPage }) => { await pmPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pmPage.waitForLoadState('networkidle').catch(() => { }); await pmPage.waitForTimeout(2000); const b = await pmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI2: PEPM sees full invoice form', async ({ pepmPage }) => { await pepmPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pepmPage.waitForLoadState('networkidle').catch(() => { }); await pepmPage.waitForTimeout(2000); const b = await pepmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI3: Manager implicit custody tracked', async ({ adminPage }) => { await adminPage.goto('/projects', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI4: managerSpent visible in project', async ({ adminPage }) => { await adminPage.goto('/projects', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const l = adminPage.locator('a[href*="/projects/"]').first(); if (await l.count() > 0) { await l.click(); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); } const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI5: Implicit custody limit = available budget', async ({ adminPage }) => { await adminPage.goto('/projects', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI6: Manager invoice auto-detects source', async ({ pmPage }) => { await pmPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pmPage.waitForLoadState('networkidle').catch(() => { }); await pmPage.waitForTimeout(2000); const b = await pmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI7: Manager creates purchase', async ({ pmPage }) => { await pmPage.goto('/purchases/new', { waitUntil: 'domcontentloaded' }); await pmPage.waitForLoadState('networkidle').catch(() => { }); await pmPage.waitForTimeout(2000); const b = await pmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IMI8: PE cannot create purchase', async ({ pePage }) => { await pePage.goto('/purchases', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(20); });
    test('P9-IMI9: PEPM can access both invoices and purchases', async ({ pepmPage }) => { await pepmPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await pepmPage.waitForLoadState('networkidle').catch(() => { }); await pepmPage.waitForTimeout(2000); expect(pepmPage.url()).toContain('/invoices'); });
    test('P9-IMI10: PEPM can access purchases', async ({ pepmPage }) => { await pepmPage.goto('/purchases', { waitUntil: 'domcontentloaded' }); await pepmPage.waitForLoadState('networkidle').catch(() => { }); await pepmPage.waitForTimeout(2000); const b = await pepmPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
});

test.describe('P9-IEA: Invoice Edge Amounts', () => {
    test('P9-IEA1: Zero amount rejected', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA2: Negative amount rejected', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA3: Very large amount handled', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA4: Fractional amount handled', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA5: Amount > custody balance blocked', async ({ pePage }) => { await pePage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IEA6: Amount = custody balance closes custody', async ({ pePage }) => { await pePage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IEA7: NaN amount rejected', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA8: Currency formatting in amounts', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IEA9: Amount thousands separator', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IEA10: Invoice notes field optional', async ({ pePage }) => { await pePage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await pePage.waitForLoadState('networkidle').catch(() => { }); await pePage.waitForTimeout(2000); const b = await pePage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IEA11: Invoice date field', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA12: Invoice vendor field', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA13: Invoice file upload preview', async ({ adminPage }) => { await adminPage.goto('/invoices/new', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(100); });
    test('P9-IEA14: Invoice search by reference', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
    test('P9-IEA15: Invoice pagination or load more', async ({ adminPage }) => { await adminPage.goto('/invoices', { waitUntil: 'domcontentloaded' }); await adminPage.waitForLoadState('networkidle').catch(() => { }); await adminPage.waitForTimeout(2000); const b = await adminPage.textContent('body') || ''; expect(b.length).toBeGreaterThan(50); });
});
